package Telas;


import Classes.livro;
import BD.Consulta;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Matheus Estevam
 */
public class ConsultarLivros extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarLivros
     */
    DefaultTableModel Modelo;
    public ConsultarLivros() {
        initComponents();
        Modelo = (DefaultTableModel) jTable1.getModel();
        titulo.setVisible(false);
        genero.setVisible(false);
        autor.setVisible(false);
        editora.setVisible(false);
        consulta();
        ChangeIndice();
    }
    
    public void consulta(){
        Modelo.setNumRows(0);
        Consulta produtos = new Consulta();        
        for (livro atr: produtos.ConsultarLivro()) {
            Modelo.addRow(new Object[]{atr.getNome(),atr.getEditora(),atr.getGenero(),atr.getAutor()});
        }
        produtos.FecharConexao();
    }
    
    public void ChangeIndice(){
       int num = comboBox.getSelectedIndex();
       switch (num) {
           case 0:
               titulo.setVisible(true);
               genero.setVisible(false);
               autor.setVisible(false);
               editora.setVisible(false);
               genero.setText("");
               autor.setText("");
               editora.setText("");
               consulta();
               break;
           case 1:
               editora.setVisible(true);
               genero.setVisible(false);
               autor.setVisible(false);
               titulo.setVisible(false);
               genero.setText("");
               autor.setText("");
               titulo.setText("");
               consulta();
               break;
           case 2:
               genero.setVisible(true);
               editora.setVisible(false);
               autor.setVisible(false);
               titulo.setVisible(false);
               editora.setText("");
               autor.setText("");
               titulo.setText("");
               consulta();
               break;
           case 3:
               autor.setVisible(true);
               editora.setVisible(false);
               genero.setVisible(false);
               titulo.setVisible(false);
               titulo.setText("");
               genero.setText("");
               editora.setText("");
               consulta();
               break;
           default:
               break;
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        genero = new javax.swing.JTextField();
        autor = new javax.swing.JTextField();
        editora = new javax.swing.JTextField();
        comboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(38, 105, 145));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -5, 1370, 60));

        jLabel2.setFont(new java.awt.Font("Harrington", 0, 48)); // NOI18N
        jLabel2.setText("Pesquisar Acervo ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 490, 60));

        jLabel3.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jLabel3.setText("Nome do Livro: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 250, 30));
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 620, 30));
        jPanel1.add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 620, 30));
        jPanel1.add(autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 620, 30));
        jPanel1.add(editora, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 620, 30));

        comboBox.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Título", "Editora", "Gênero", "Autor" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 200, 30));

        jLabel4.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jLabel4.setText("Pesquisar em...");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 190, 30));

        jTable1.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Editora", "Gênero", "Autor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 1000, 310));

        jButton1.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 240, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1369, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            if(titulo.getText().equals("") && genero.getText().equals("") && autor.getText().equals("") && editora.getText().equals("")){
                consulta();
            }else{
                int inidice = comboBox.getSelectedIndex();

                Modelo.setNumRows(0);
                Consulta atr = new Consulta();        
                for (livro livro: atr.ConsultarLivro(titulo.getText(),editora.getText(),genero.getText(), autor.getText(), inidice)) {
                     Modelo.addRow(new Object[]{livro.getNome(),livro.getEditora(),livro.getGenero(),livro.getAutor()});
                }
                atr.FecharConexao();
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        ChangeIndice();
    }//GEN-LAST:event_comboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autor;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JTextField editora;
    private javax.swing.JTextField genero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
